# Diwa Dev Context Restoration - COMPREHENSIVE
# Rebuilt from Claude's conversation history on 2025-01-09
# Run with: mix run restore_diwa_dev_comprehensive.exs

alias DiwaAgent.Repo
alias DiwaSchema.Core.Context
alias DiwaSchema.Core.ContextRelationship
import Ecto.Query

IO.puts("🔄 Starting comprehensive diwa_dev restoration...")
IO.puts("   Source: Claude conversation history")
IO.puts("   Incident: Antigravity ran `mix ecto.reset` without confirmation")
IO.puts("")

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

defmodule RestoreHelpers do
  def create_context(repo, attrs) do
    # Map metadata to proper structure if needed
    context_uuid = attrs[:id]
    
    # Check if exists
    case repo.get(DiwaSchema.Core.Context, context_uuid) do
      nil ->
         # Explicitly set ID in struct to ensure it is used, instead of autogenerated
         %DiwaSchema.Core.Context{id: context_uuid}
         |> DiwaSchema.Core.Context.changeset(Map.put(attrs, :organization_id, "c075ee3c-9df9-4e72-8d75-cf6debb789ac")) # Default Org
         |> repo.insert!(on_conflict: :nothing)
      existing -> existing
    end
  end
  
  def create_memory(repo, attrs) do
    # Map deprecated fields to map/metadata if needed
    # memory_type -> memory_class or metadata
    type = attrs[:memory_type]
    attrs = attrs 
            |> Map.put(:memory_class, type)
            |> Map.delete(:memory_type)
            # Map importance -> priority or severity
            |> Map.put(:priority, if(attrs[:importance] >= 9, do: "High", else: "Medium"))
            |> Map.delete(:importance)

    %DiwaSchema.Core.Memory{}
    |> DiwaSchema.Core.Memory.changeset(attrs)
    |> repo.insert!(on_conflict: :nothing)
  end
  
  def create_decision(repo, attrs) do
    # Map Decision -> Memory (class: decision)
    content = """
    # DECISION: #{attrs[:title]}
    
    #{attrs[:description]}
    
    **Reasoning:** #{attrs[:reasoning]}
    **Outcome:** #{attrs[:outcome]}
    **Confidence:** #{attrs[:confidence]}%
    """
    
    metadata = %{
      type: "decision",
      title: attrs[:title],
      outcome: attrs[:outcome],
      confidence: attrs[:confidence]
    }
    
    %DiwaSchema.Core.Memory{}
    |> DiwaSchema.Core.Memory.changeset(%{
         context_id: attrs[:context_id],
         content: content,
         memory_class: "decision",
         metadata: metadata
       })
    |> repo.insert!(on_conflict: :nothing)
  end
  
  def create_requirement(repo, attrs) do
    # Map Requirement -> Task
    
    # Priority Mapping
    priority_input = attrs[:priority] || "Medium"
    priority = case String.downcase(priority_input) do
      "critical" -> "High"
      "high" -> "High"
      "medium" -> "Medium"
      "low" -> "Low"
      _ -> "Medium"
    end

    %DiwaSchema.Team.Task{}
    |> DiwaSchema.Team.Task.changeset(%{
         context_id: attrs[:context_id],
         title: attrs[:title],
         description: attrs[:description],
         priority: priority,
         status: if(attrs[:status] == "completed", do: "completed", else: "pending")
       })
    |> repo.insert!(on_conflict: :nothing)
  end
  
  def create_relationship(repo, attrs) do
    try do
      %DiwaSchema.Core.ContextRelationship{}
      |> DiwaSchema.Core.ContextRelationship.changeset(%{
           source_context_id: attrs[:source],
           target_context_id: attrs[:target],
           relationship_type: attrs[:type]
         })
      |> repo.insert!(on_conflict: :nothing)
      IO.write(".")
    rescue
      e ->
        IO.puts("\n❌ FAILED RELATIONSHIP: #{inspect(attrs)}")
        source = attrs[:source]
        target = attrs[:target]
        source_exists = repo.get(DiwaSchema.Core.Context, source) != nil
        target_exists = repo.get(DiwaSchema.Core.Context, target) != nil
        IO.puts("   Source (#{source}) Exists? #{source_exists}")
        IO.puts("   Target (#{target}) Exists? #{target_exists}")
        reraise e, __STACKTRACE__
    end
  end
end

# Ensure Org exists
Repo.query!("""
INSERT INTO organizations (id, name, tier, inserted_at, updated_at)
VALUES ('c075ee3c-9df9-4e72-8d75-cf6debb789ac', 'Default', 'free', NOW(), NOW())
ON CONFLICT (id) DO NOTHING
""")

# =============================================================================
# 1. CREATE CONTEXTS (with original UUIDs where known)
# =============================================================================

IO.puts("📂 Creating contexts...")

contexts = [
  %{
    id: "436b3760-b355-4ae1-878b-7f29d91546af",
    name: "Project DIWA",
    description: "Master spec, release strategy, v3.0 implementation. Central intelligence platform for the Filipino AI Stack.",
    # metadata is not a semantic field in Context schema usually (it is embedded in struct?)
    # Context schema has no :metadata field according to Ecto Schema! 
    # Let's verify schema... 
    # Context schema: name, description, health_score, organization_id, sync_origin, remote_id
    # NO metadata field. We will drop metadata.
  },
  %{
    id: "601d57b6-c47d-42b1-b733-4d240f6e7353",
    name: "Project UGAT",
    description: "Universal Graph Analysis Tools - Context backbone, auto-detection, graph traversal. Week 0 focus area."
  },
  %{
    id: "3c105467-741f-4240-a85f-ac249fdb246f",
    name: "Project WIKA",
    description: "Widely Integrated Knowledge Architecture - Communication protocol."
  },
  %{
    id: "2d383217-4520-4f76-83f6-d9b93b1fc9a9",
    name: "Project SINAG",
    description: "Synthetic Inference & Neural Agent Grid - Agent runtime layer."
  },
  %{
    id: "bbf1bd93-7a57-411b-a144-a17ca4093ccc",
    name: "Project ISIP",
    description: "Inference Semantic Isolation Protocol - Rust kernel, OS primitives layer."
  },
  %{
    id: "89867683-3f0f-4c34-9b10-59bc4e09f7f0",
    name: "Project TANAW",
    description: "Multi-agent dashboard for unified planning and development workflows."
  },
  %{
    id: "0fbe494e-8fae-4866-8dfc-9a6cef7f8cb3",
    name: "Project TINIG",
    description: "Voice features - Patents #4 AGVM, #9 CVMI."
  },
  %{
    id: "66fa9798-6946-49a5-a4f6-d54894e4fa23",
    name: "Project ALAM",
    description: "Knowledge and learning module."
  },
  %{
    id: "60b5ba56-9483-4580-8ddc-49091ec52bc3",
    name: "Diwa-Web",
    description: "Website at diwa.one"
  },
  %{
    id: "b4a9fbc8-167e-46ba-aab0-9b4896918b6b",
    name: "Diwa Product",
    description: "User-facing documentation and product features"
  },
  %{
    id: "6e5c169d-bec6-40c5-aa8d-f961c7f94e05",
    name: "Diwa Enterprise v2.0",
    description: "Enterprise features context - Conflict Engine, Phase 3 specs, production roadmap"
  },
  %{
    id: "642ad022-f5bf-4c52-aa56-ef82cad04ccf",
    name: "Project UGAT - Filipino AI Stack",
    description: "Unified context for Filipino AI Stack development."
  }
]

Enum.each(contexts, fn ctx ->
  RestoreHelpers.create_context(Repo, ctx)
  IO.puts("   ✓ #{ctx.name}")
end)

IO.puts("✅ Created #{length(contexts)} contexts")
IO.puts("")

# =============================================================================
# 2. CREATE CONTEXT RELATIONSHIPS (16 links)
# =============================================================================

IO.puts("🔗 Creating context relationships...")

relationships = [
  # UGAT contains all
  %{source: "601d57b6-c47d-42b1-b733-4d240f6e7353", target: "436b3760-b355-4ae1-878b-7f29d91546af", type: "contains"},
  %{source: "601d57b6-c47d-42b1-b733-4d240f6e7353", target: "2d383217-4520-4f76-83f6-d9b93b1fc9a9", type: "contains"},
  %{source: "601d57b6-c47d-42b1-b733-4d240f6e7353", target: "bbf1bd93-7a57-411b-a144-a17ca4093ccc", type: "contains"},
  %{source: "601d57b6-c47d-42b1-b733-4d240f6e7353", target: "89867683-3f0f-4c34-9b10-59bc4e09f7f0", type: "contains"},
  %{source: "601d57b6-c47d-42b1-b733-4d240f6e7353", target: "3c105467-741f-4240-a85f-ac249fdb246f", type: "contains"},
  %{source: "601d57b6-c47d-42b1-b733-4d240f6e7353", target: "0fbe494e-8fae-4866-8dfc-9a6cef7f8cb3", type: "contains"},
  %{source: "601d57b6-c47d-42b1-b733-4d240f6e7353", target: "66fa9798-6946-49a5-a4f6-d54894e4fa23", type: "contains"},
  
  # Dependencies
  %{source: "2d383217-4520-4f76-83f6-d9b93b1fc9a9", target: "436b3760-b355-4ae1-878b-7f29d91546af", type: "depends_on"},
  %{source: "89867683-3f0f-4c34-9b10-59bc4e09f7f0", target: "436b3760-b355-4ae1-878b-7f29d91546af", type: "depends_on"},
  %{source: "89867683-3f0f-4c34-9b10-59bc4e09f7f0", target: "2d383217-4520-4f76-83f6-d9b93b1fc9a9", type: "depends_on"},
  
  # ISIP complements SINAG
  %{source: "bbf1bd93-7a57-411b-a144-a17ca4093ccc", target: "2d383217-4520-4f76-83f6-d9b93b1fc9a9", type: "complements"},
  
  # WIKA implementations
  %{source: "3c105467-741f-4240-a85f-ac249fdb246f", target: "436b3760-b355-4ae1-878b-7f29d91546af", type: "implements"},
  %{source: "436b3760-b355-4ae1-878b-7f29d91546af", target: "3c105467-741f-4240-a85f-ac249fdb246f", type: "implements"},
  %{source: "2d383217-4520-4f76-83f6-d9b93b1fc9a9", target: "3c105467-741f-4240-a85f-ac249fdb246f", type: "implements"},
  
  # Extensions
  %{source: "0fbe494e-8fae-4866-8dfc-9a6cef7f8cb3", target: "436b3760-b355-4ae1-878b-7f29d91546af", type: "extends"},
  %{source: "66fa9798-6946-49a5-a4f6-d54894e4fa23", target: "436b3760-b355-4ae1-878b-7f29d91546af", type: "extends"}
]

Enum.each(relationships, fn rel ->
  RestoreHelpers.create_relationship(Repo, rel)
end)

IO.puts("✅ Created #{length(relationships)} relationships")
IO.puts("")

# =============================================================================
# 3. CREATE MEMORIES (Core Architecture & Key Information)
# =============================================================================

IO.puts("🧠 Creating memories...")

# Primary context for most memories
diwa_context = "436b3760-b355-4ae1-878b-7f29d91546af"
ugat_context = "601d57b6-c47d-42b1-b733-4d240f6e7353"
enterprise_context = "6e5c169d-bec6-40c5-aa8d-f961c7f94e05"

memories = [
  # === ARCHITECTURE ===
  %{
    context_id: diwa_context,
    content: """
    # Filipino AI Stack Master Architecture v2.0
    
    ## Three Planes
    - **Cloud Plane:** LANGIT, TIPAN, GILAS, TANAW
    - **Node Plane:** KUBO, GABAY, SINAG, ALAM, TALINO, DIWA, GAWA
    - **Kernel Plane:** ISIP
    
    ## Governing Framework
    YHWH as outer governance (sets boundaries) and inner core (source of computation)
    "For from Him and through Him and to Him are all things." — Romans 11:36
    
    ## Cultural Principle
    "Ang wika ang kaluluwa ng bansa" — Language is the soul of a nation
    """,
    memory_type: "architecture",
    tags: ["master", "v2.0", "canonical"],
    importance: 10
  },
  %{
    context_id: diwa_context,
    content: """
    # Dual MCP Architecture
    
    ## Configuration
    - **diwa-agent**: Port 4000, Apache 2.0 (open source)
    - **diwa-cloud**: Port 7007, BSL (proprietary)
    - **Shared**: PostgreSQL database (diwa_dev)
    
    ## Key Insight
    Claude Desktop natively supports multiple MCP servers.
    No Gateway needed for local development - each repo runs its own MCP server.
    
    ## Setup (claude_desktop_config.json)
    ```json
    {
      "mcpServers": {
        "diwa-agent": {"command": "/path/to/diwa-agent/diwa.sh", "args": ["start"]},
        "diwa-cloud": {"command": "/path/to/diwa-cloud/diwa.sh", "args": ["start"]}
      }
    }
    ```
    """,
    memory_type: "architecture",
    tags: ["mcp", "dual", "configuration"],
    importance: 10
  },
  
  # === WIKA PROTOCOL ===
  %{
    context_id: "3c105467-741f-4240-a85f-ac249fdb246f",
    content: """
    # WIKA Protocol Specification v1.0
    
    **Name:** WIKA (Widely Integrated Knowledge Architecture)
    **Filipino:** "Wika" = Language
    **Evolution:** From data schema spec to "TCP/IP of AI agents"
    
    ## The Six Sub-Specifications
    | Sub-Spec | Filipino | Purpose |
    |----------|----------|---------|
    | MENSAHE | Message | Message protocol and envelope format |
    | HANGAD | Intent/Desire | Intent and goal expression language |
    | PATAKARAN | Policy/Rule | Policy definition language (for TIPAN) |
    | PANGYAYARI | Event/Happening | Event schema for observability |
    | KALAGAYAN | State/Condition | State and data schemas |
    | TIRAHAN | Address/Location | Addressing and discovery |
    
    ## Serialization
    - MessagePack (default, binary)
    - JSON (debugging)
    - Protocol Buffers (cross-language)
    
    ## Transports
    - BEAM Messages (Node)
    - TCP/TLS (Cloud ↔ Node)
    - gRPC (Cloud ↔ Cloud)
    - WebSocket (Browser ↔ Cloud)
    - Unix Sockets (Node ↔ Kernel)
    """,
    memory_type: "specification",
    tags: ["wika", "protocol", "v1.0"],
    importance: 10
  },
  
  # === COMPLETED MILESTONES ===
  %{
    context_id: ugat_context,
    content: """
    # diwa_schema v0.1.0 Published to Hex.pm ✅
    
    **Date:** January 7, 2026
    **Package:** https://hex.pm/packages/diwa_schema/0.1.0
    **Docs:** https://hexdocs.pm/diwa_schema/0.1.0
    **GitHub:** https://github.com/diwahq/diwa_schema
    
    ## Status
    - All 8 phases complete
    - 514/514 tests passing
    - Zero schema drift achieved
    - Both repos using `{:diwa_schema, "~> 0.1"}`
    - Community launch UNBLOCKED
    
    ## Impact
    Contributors can now run `mix ecto.migrate` from the open-source diwa-agent repo.
    """,
    memory_type: "milestone",
    tags: ["diwa_schema", "hex", "complete"],
    importance: 10
  },
  %{
    context_id: enterprise_context,
    content: """
    # Conflict Engine Phase 3 Complete ✅
    
    ## Features Implemented
    - Autonomous background workers
    - LLM-based structured judging
    - Hierarchical conflict arbitration
    - Full web interface for human oversight at /conflicts
    
    ## Resolution Tiers
    - Tier 1: Auto-synthesis via LLM
    - Tier 2: Human review
    - Tier 3: Admin escalation
    
    ## Next Steps (P1)
    - Visual Graph: D3/Mermaid visualization of conflict family trees
    - PromEx Metrics: Track conflict rates and resolution types
    """,
    memory_type: "milestone",
    tags: ["conflict_engine", "phase3", "complete"],
    importance: 9
  },
  
  # === WORKFLOW & RULES ===
  %{
    context_id: diwa_context,
    content: """
    # Rule 1 Compliance
    
    All specifications must follow "Rule 1":
    - Function signatures only
    - Business logic descriptions
    - NO implementation code
    - Designed for handoff to AI coders (Antigravity/Gemini)
    
    ## Required Fields
    - `repo: diwa-agent|diwa-cloud` — Which codebase implements the feature
    - `priority: P0|P1|P2|P3` — Implementation priority
    - `effort: Xh` — Estimated hours
    
    ## Example
    ```elixir
    @doc "Build graph from a single conflict resolution outcome"
    @spec from_outcome(outcome :: map()) :: %{nodes: [node()], edges: [edge()]}
    ```
    """,
    memory_type: "principle",
    tags: ["rule1", "specifications", "workflow"],
    importance: 10
  },
  
  # === LICENSING & BUSINESS ===
  %{
    context_id: diwa_context,
    content: """
    # Distribution Strategy: 60/30/10
    
    | Tier | License | Content |
    |------|---------|---------|
    | 60% | Apache 2.0 | Open source community features |
    | 30% | BSL 1.1 | Source-available team features |
    | 10% | Proprietary | Enterprise features |
    """,
    memory_type: "business",
    tags: ["licensing", "60-30-10", "tiers"],
    importance: 9
  },
  
  # === COLLABORATORS ===
  %{
    context_id: diwa_context,
    content: """
    # AI Collaborators
    
    | Agent | Role | Model | Cost |
    |-------|------|-------|------|
    | Claude | Planning, specifications | Sonnet/Opus | $3/1M tokens |
    | Antigravity | Code implementation | Gemini | $2/1M tokens |
    
    ## Workflow
    1. Claude creates Rule 1 compliant specs
    2. Antigravity implements code
    3. Claude reviews and iterates
    
    ## Known Issues
    - Antigravity ran `mix ecto.reset` without confirmation (2025-01-09)
    - MCP "invalid trailing data" errors causing connection instability
    
    ## Safeguard Needed
    Add to Antigravity system prompt:
    > "NEVER run destructive database commands (mix ecto.reset, mix ecto.drop, DROP TABLE, TRUNCATE) without explicit user confirmation."
    """,
    memory_type: "team",
    tags: ["collaborators", "claude", "antigravity"],
    importance: 9
  },
  
  # === KNOWN ISSUES ===
  %{
    context_id: enterprise_context,
    content: """
    # MCP Connection Instability
    
    **Symptom:** "invalid trailing data" errors in MCP connections
    **Impact:** Prevents tool-based handoff notes, session workflows
    **Priority:** P0 (blocking)
    
    ## Workarounds
    1. Use `add_memory` with tag `handoff` instead of `set_handoff_note`
    2. Manually write to `/mnt/user-data/outputs/handoff.md`
    3. Use shorter messages to reduce concatenation risk
    
    ## Investigation Needed
    - Add debug logging to capture raw bytes
    - Check Hermes MCP version
    - Identify framing issue
    - Consider WebSocket transport as alternative
    """,
    memory_type: "known_issue",
    tags: ["mcp", "instability", "blocking"],
    importance: 9
  }
]

Enum.each(memories, fn mem ->
  RestoreHelpers.create_memory(Repo, mem)
end)

IO.puts("✅ Created #{length(memories)} memories")
IO.puts("")

# =============================================================================
# 4. CREATE DECISIONS (Mapped to Memories)
# =============================================================================

IO.puts("⚖️ Creating decisions...")

decisions = [
  %{
    context_id: diwa_context,
    title: "Dual MCP Architecture",
    description: "diwa-agent (4000) and diwa-cloud (7007) share PostgreSQL, eliminating Gateway",
    reasoning: "Claude Desktop natively supports multiple MCP servers. Simpler architecture, no tool sync needed.",
    outcome: "approved",
    confidence: 95
  },
  %{
    context_id: "3c105467-741f-4240-a85f-ac249fdb246f",
    title: "WIKA as TCP/IP for AI Agents",
    description: "WIKA evolved from data schema spec to communication backbone protocol",
    reasoning: "Need standardized agent-to-agent networking layer. 'Language is the soul of a nation' fits perfectly.",
    outcome: "approved",
    confidence: 90
  },
  %{
    context_id: diwa_context,
    title: "60/30/10 Distribution Strategy",
    description: "60% Apache 2.0, 30% BSL, 10% Proprietary",
    reasoning: "Balance open source community building with sustainable business model",
    outcome: "approved",
    confidence: 85
  },
  %{
    context_id: ugat_context,
    title: "diwa_schema Extraction to Hex.pm",
    description: "Extract shared schemas to separate package, published v0.1.0",
    reasoning: "Enable both diwa-agent and diwa-cloud to share types cleanly. Unblock Community launch.",
    outcome: "completed",
    confidence: 100
  },
  %{
    context_id: enterprise_context,
    title: "Phase 3 Post-Completion Priorities",
    description: "P0=MCP instability, P1=PromEx metrics + Visual Graph",
    reasoning: "MCP instability blocks session workflows. Metrics and visualization enhance Conflict Engine.",
    outcome: "approved",
    confidence: 90
  },
  %{
    context_id: "642ad022-f5bf-4c52-aa56-ef82cad04ccf",
    title: "TANAW IP Strategy: BSL + DIWA Documentation",
    description: "Protect IP via BSL licensing and DIWA documentation, defer patents until fundraising",
    reasoning: "Patents expensive (~$15k/patent). BSL provides protection. DIWA timestamped prior art.",
    outcome: "approved",
    confidence: 85
  }
]

Enum.each(decisions, fn dec ->
  RestoreHelpers.create_decision(Repo, dec)
end)

IO.puts("✅ Created #{length(decisions)} decisions")
IO.puts("")

# =============================================================================
# 5. CREATE REQUIREMENTS (Mapped to Tasks)
# =============================================================================

IO.puts("📋 Creating requirements (tasks)...")

requirements = [
  # Completed
  %{context_id: ugat_context, title: "Extract diwa_schema Shared Library", priority: "high", status: "completed", description: "Published to Hex.pm v0.1.0"},
  %{context_id: ugat_context, title: "Implement get_context_graph", priority: "high", status: "completed", description: "UGAT tool for context relationships"},
  %{context_id: ugat_context, title: "Establish 16 Context Relationships", priority: "high", status: "completed", description: "Filipino AI Stack component links"},
  %{context_id: enterprise_context, title: "Conflict Engine Phase 3", priority: "high", status: "completed", description: "Autonomous workers, LLM judging, web UI"},
  
  # In Progress
  %{context_id: enterprise_context, title: "MCP Connection Stability", priority: "critical", status: "in_progress", description: "Fix 'invalid trailing data' errors. P0 blocking."},
  %{context_id: enterprise_context, title: "PromEx Metrics for Conflict Engine", priority: "high", status: "planned", description: "Track conflict rates, resolution distribution, synthesis quality"},
  %{context_id: enterprise_context, title: "Conflict Family Tree Visualization", priority: "high", status: "planned", description: "Mermaid graph for /conflicts view"},
  
  # Planned
  %{context_id: ugat_context, title: "Smart Session Onboarding UX", priority: "medium", status: "planned", description: "Improve UX when context detection fails. ~4-6h"},
  %{context_id: ugat_context, title: "UGAT Gateway (Meta-MCP)", priority: "low", status: "planned", description: "Federation for multi-instance. ~20h. Not blocking."},
  %{context_id: "642ad022-f5bf-4c52-aa56-ef82cad04ccf", title: "Implement tanaw-lite", priority: "high", status: "planned", description: "Apache 2.0 community dashboard. ~42h"},
  %{context_id: "642ad022-f5bf-4c52-aa56-ef82cad04ccf", title: "Implement Additional Shortcuts", priority: "medium", status: "planned", description: "@specs, @decisions, @lessons, @blockers, @pending, @health, @search. ~1h"},
  %{context_id: "bbf1bd93-7a57-411b-a144-a17ca4093ccc", title: "ISIP Repository Audit", priority: "high", status: "planned", description: "Repository mistakenly made public, needs privacy restoration"},
  %{context_id: "2d383217-4520-4f76-83f6-d9b93b1fc9a9", title: "SINAG Dependencies Documentation", priority: "medium", status: "planned", description: "29 dependencies, only 4 documented"},
  
  # New from incident
  %{context_id: diwa_context, title: "Destructive Operation Safeguards", priority: "critical", status: "planned", description: "Require confirmation for mix ecto.reset, DROP TABLE, etc. Add to Antigravity system prompt."}
]

Enum.each(requirements, fn req ->
  RestoreHelpers.create_requirement(Repo, req)
end)

IO.puts("✅ Created #{length(requirements)} requirements")
IO.puts("")

# =============================================================================
# 6. SET HANDOFF NOTE
# =============================================================================

IO.puts("📝 Setting handoff note...")

# Create/Update Plan with status/notes for this session
Repo.query!("""
INSERT INTO plans (id, context_id, status, completion_pct, notes, inserted_at, updated_at)
VALUES ('#{Ecto.UUID.generate()}', '#{ugat_context}', 'Active', 50, $1, NOW(), NOW())

""", [
  """
  Context restored after accidental data loss from `mix ecto.reset` by Antigravity.
  
  ## Completed
  - diwa_schema v0.1.0 on Hex.pm - Community launch unblocked
  - Conflict Engine Phase 3 complete
  - 16 context relationships established
  - get_context_graph implemented
  
  ## Current Focus
  - Week 0 UGAT priorities (mostly complete)
  - MCP stability investigation (P0 blocking)
  """
])

IO.puts("✅ Handoff note set (Plan updated)")
IO.puts("")

IO.puts("🎉 RESTORATION COMPLETE!")
